VOICEMAIL_PAIRS = [
  ("mother", "son"),
  ("mother", "daughter"),
  ("father", "son"),
  ("father", "daughter"),
  ("grandmother", "grandson"),
  ("grandmother", "granddaughter"),
  ("grandfather", "grandson"),
  ("grandfather", "granddaughter"),
  ("aunt", "nephew"),
  ("aunt", "niece"),
  ("uncle", "nephew"),
  ("uncle", "niece"),
  ("sister", "brother"),
  ("sister", "sister"),
  ("brother", "brother"),
  ("brother", "sister"),
  ("cousin", "cousin"),
  ("doctor", "patient"),
  ("teacher", "student"),
  ("boss", "employee"),
  ("friend", "friend"),
  ("neighbor", "neighbor"),
  ("girlfriend", "boyfriend"),
  ("girlfriend", "girlfriend"),
  ("boyfriend", "boyfriend"),
  ("boyfriend", "girlfriend"),
  ("wife", "husband"),
  ("wife", "wife"),
  ("husband", "husband"),
  ("husband", "wife"),
  ("family member", "college student"),
  ("family member", "high school student"),
  ("family member", "middle school student"),
  ("family member", "elementary school student"),
  ("landlord", "tenant"),
  ("coach", "athlete"),
  ("mentor", "mentee"),
  ("landlord", "tenant"),
  ("coach", "athlete"),
  ("mentor", "mentee"),
  ("advisor", "advisee"),
  ("therapist", "client"),
  ("lawyer", "client"),
  ("hairdresser", "client"),
  ("mechanic", "customer"),
  ("dentist", "patient"),
  ("veterinarian", "pet owner"),
  ("babysitter", "parent"),
  ("stepmother", "stepson"),
  ("stepmother", "stepdaughter"),
  ("stepfather", "stepson"),
  ("stepfather", "stepdaughter"),
  ("half-sister", "half-brother"),
  ("half-sister", "half-sister"),
  ("half-brother", "half-sister"),
  ("foster parent", "foster child"),
  ("godmother", "godson"),
  ("godmother", "goddaughter"),
  ("godfather", "godson"),
  ("godfather", "goddaughter"),
  ("roommate", "roommate"),
  ("business partner", "business partner"),
  ("coworker", "coworker"),
  ("tutor", "tutee"),
  ("best man", "groom"),
  ("maid of honor", "bride"),
  ("bride", "groom"),
  ("bridesmaid", "bride"),
  ("groomsman", "groom"),
  ("parent", "teacher"),
  ("salesperson", "customer"),
  ("realtor", "homebuyer"),
  ("insurance agent", "client"),
  ("travel agent", "client"),
  ("artist", "art collector"),
  ("photographer", "client"),
  ("personal trainer", "client"),
  ("caregiver", "care recipient"),
  ("pen pal", "pen pal"),
  ("fiancé", "fiancée"),
  ("ex-husband", "ex-wife"),
  ("ex-boyfriend", "ex-girlfriend"),
  ("instructor", "participant"),
  ("volunteer", "organizer"),
  ("support group member", "support group member"),
  ("group leader", "group member"),
  ("podcast host", "guest"),
  ("journalist", "interviewee"),
  ("food delivery driver", "resident")
]

MEN_ROLES = [
    "son",
    "father",
    "grandson",
    "grandfather",
    "nephew",
    "uncle",
    "brother",
    "father",
    "boyfriend",
    "husband",
    "boyfriend",
    "husband",
    "stepson",
    "stepfather",
    "half-brother",
    "godson",
    "godfather",
    "best man",
    "groom",
    "groomsman",
    "ex-husband",
    "ex-boyfriend",
]

WOMEN_ROLES = [
    "mother",
    "daughter",
    "grandmother",
    "granddaughter",
    "aunt",
    "niece",
    "sister",
    "girlfriend",
    "wife",
    "stepmother",
    "half-sister",
    "godmother",
    "maid of honor",
    "bride",
    "bridesmaid",
    "bride",
    "fiancée",
    "ex-wife",
    "ex-girlfriend",
]

ELEVEN_LABS_MEN_NAMES = [
    'Antoni',
    'Elli',
    'Josh',
    'Arnold',
    'Adam',
]

ELEVEN_LABS_WOMEN_NAMES = [
    'Rachel',
    'Bella',
    'Sam',
    'Domi'
    'grandmother-1',
]


DATA_TYPE="float32"